version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: yasir
      POSTGRES_PASSWORD: yasir1995
      POSTGRES_DB: school
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
  app:
    build: .
    container_name: nextjs_app
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: "postgresql://yasir:yasir1995@localhost:5432/school?schema=public"
    depends_on:
      - postgres

volumes:
  postgres_data: